### ISSUE TITLE
Placeholder: proximity

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#216]
This includes the whole circus. Blocked by #60 for some parts because in #60 we'll define the feature mechanism and opt-in/out.

TODO:
 * [x] Contest activity UI (done in #241)
    * "In progress" state
    * "Completed" state
 * [x] Show contest state in preferences if enabled (tapping it shows the contest activity) (done in #241)
 * [x] "In this room" snackbar in homescreen (done in #221)
 * [x] Missing prerequisites snackbar in homescreen
 * [x] Opt in/out from settings (done in #240)
 * [x] Venue notification setup
 * [x] Redeem instructions (done in #241)

**Comment by rock3r** [comment]
CC @catt-stefano let's keep track of progress here

**Comment by catt-stefano** [comment]
The snackbar feature is implemented by https://github.com/rock3r/squanchy/pull/221

**Comment by catt-stefano** [comment]
I'm working on the opt in/out toggle

**Comment by catt-stefano** [comment]
Opt in/out toggle from settings implemented by https://github.com/rock3r/squanchy/pull/240

**Comment by catt-stefano** [comment]
TODO: change current proximity event snackbar text to show "Right now" instead of current time

**Comment by catt-stefano** [comment]
This is for our trackings https://github.com/rock3r/squanchy/pull/246

**Comment by rock3r** [comment]
All done
