### ISSUE TITLE
Simplify project setup

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#344]
- [x] #343 Remove references to unused Google Maps API key
 - [x] #275 Make debug keystore part of the project conf
 - [x] #345 Provide example database dump to import into Firebase
 - [x] #346 Detail Firebase project setup and gotchas (venue image URL, auth, etc)
 - [x] #389 Better handling of missing app config

**Comment by rock3r** [comment]
#345 and #346 do not apply anymore: we're moving away from RTDB and there is no import/export tool in Firestore.

**Comment by rock3r** [comment]
#389 should be done in the properties plugin, I suppose; I will open a ticket there.
