### ISSUE TITLE
Screen: onboarding

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#60]
Three pages:
 * [x] **Contest/location opt-in** (done in #211, #213)
    * Prompts for location permission
    * If BLE is off, offers to turn it on
    * Enables NearIt when both are on
 * [x] **Account sign-in** (done in #319)
    * Pops up the sign-in bottom sheet
 * [ ] **WiFi pre-configuration** (depends on #59)
    * During onboarding, if the wifi configuration is available, we should prompt users if they want us to autoconfigure the wifi for the conference.
 * [ ] **Analytics opt-out/GDPR readiness** (depends on #515)
    * During onboarding we should offer users the ability to opt out from analytics

**Comment by rock3r** [comment]
I love the new style @ScribblyPixels -- I was thinking, maybe we can have a continuous flow from one screen to the next (I'm thinking vertically as if we're landing down on the Squanchy planet, as we progress in the onboarding, but feel free to ignore me). In that case we'd need a visual page indicator.

Small details: I'd have the positive action on the right as is usually the norm, and the negative action being with a different/lighter style to make it immediately clear it's negative without having to read it (as in accent for positive, light for negative, like in earlier versions, but possibly with the current layout)

**Comment by ScribblyPixels** [comment]
@rock3r Both of your comments are valid points and I am happy to make those adjustments.  My main reason for adding skip on the right was that it's closer to the right side of the screen where it links to ... but in fact, it's technically the 'negative' option, so makes sense to be left. And yeah, pagination.  I'd love to animate these.  All of them need it :). I'll look into that
